### PR TITLE
Fix template name when command has no parameter

### PR DESCRIPTION
**Pull request by Babar**
Gerhard made a patch to strip the path out of a command, but this code was only used when the command had parameters.

I had a command without parameters, and it wasn't stripped out. First commit fixes that.
Second commits just simplifies the DEBUG code. It didn't work in my version, and I have no idea why you fixed it that way before.

### CODE REVIEW

**Comment by flackem** [comment]
Hi Olivier,

I've added your first commit, thanks!

Concerning the duplicate DEBUG statements, I know that it's confusing and the opposite of elegant ;). 
But I need DEBUG already for Getopts, because if Getopts fails with a signal, it traps into the signal handler and run DEBUG there.
(see https://github.com/flackem/check_multi/commit/81ccb8fe41279ece8c0f480450a86332a4e7b230 and https://github.com/flackem/check_multi/commit/be5eef6293d4faac63f488068f783a6b165bae84)

You've said that the DEBUG statements do not work in your version - what do you mean by this?

Cheers,
-Matthias

**Comment by Babar** [comment]
Hi Matthias,
I have a version between your 2 commits (0.25), and therefore the DEBUG statements are before the GetOpt. But the way you write them is useless, as $opt{set}{verbose} will never be set, as Getopt wasn't called.
So if you really need DEBUG[1-4] to be defined, maybe:
*DEBUG1 = *DEBUG2 = *DEBUG3 = *DEBUG4 = sub {};
If I understand you properly, you need the DEBUGs if some signal is received just after the signal handler was installed, but just before the DEBUGs are created. It has nothing to do with GetOpt, except that this function is probably the only one taking more than a few milliseconds, hence the "bug" can only appear here.
Anyway, coded another try to make it cleaner:
https://github.com/Babar/check_multi/commit/4e0166cad387dd5178967714fa6dc7beeef95637
It passes all tests, and is logically equivalent to your first version, except there is no race condition at all.

**Comment by flackem** [comment]
Hi Olivier,

thanks for pointing out the race condition, I missed that. ;).

But it's not only the millisecond before Getopts: the Getopts function itself raises a signal in some cases. 
Example: take the faulty command line 'check_multi -s'. -s expects a parameter, and if it's being omitted, Getopts throws a signal.

Since verbose actually is set at compile / configure time (see lines 296/297), I moved the complete typeglobs to the var definition area: 
https://github.com/flackem/check_multi/commit/a61224b45a415eba6f0a798ece4317c0b1f1c7ab

Cheers,
-Matthias

**Comment by Babar** [comment]
Oh ok, I missed the fact that you could set some default values in configure, therefore the hash _can_ be defined.

I still dislikes the undef *DEBUG1 instead of the no warnings 'redefine'; but your call. Thanks for fixing my bug. Closing this pull request, as I consider it merged.

**Comment by flackem** [comment]
You're right, the undefs are ugly and superfluous. ;)
I replaced them with the interpreter pragma.

**Pull request closed without merging**
