### PR TITLE
allow compile default path for nagiostats

### PR DESCRIPTION
**Pull request by glensc**
so that configure time sbinpath applies (like elsewhere)

### CODE REVIEW

**Comment by flackem** [comment]
Hi Elan,

thanks, @sbindir@ is now added to nagiostats.cmd.

Cheers,
-Matthias

**Comment by glensc** [comment]
you have rather weird workflow here, so that merges do not show up as being merged. you likely merge it outside github with different vcs? but imho you could still reference at least issues/pulls with commit message, i.e #8 would reference issue 8 or pull 8 (pull seems to be something alias to issue, i.e the numbers do not overlap)

**Comment by flackem** [comment]
I see.
I'm not working with another VCS, just my local git - but if I change anything in the pull request or if it's just a oneliner, I often do a local commit and then a global push.
But you're right, for clarification it's better to add the reference number, will do next time :)

**Comment by glensc** [comment]
trivial merges can be done with github web interface. somewhere it gave you hints too how to merge with your local git, something: git merge git://github/user/repo.git sha1-hash (or branch merge whole branch) :) i'm sure "git merge" or "github merge" from google give you lots of results :)

**Pull request closed without merging**
